cjdev/visual-stack

- src/components/List.js
@lexi-lambda, are you okay with the prop names?
> add stateless ExpandedRow and ExpandedRowPanel

- src/components/Button.css
- src/components/Button.js
Created new button style for CJ Button for insights demo app.
> Add solid primary button style

- .editorconfig
- package.json
- src/components/Sidebar.css
- src/components/Sidebar.js
- test/components/SidebarTest.js
Importing Sidebar component and tests to visual stack
> Added Sidebar component

- src/components/Button.css
Found a css declaration without a closing brace. Maybe some css linting is in order?
> Fix malformed css

- .gitignore
- package.json
- src/components/Form.js
- src/components/Sidebar.js
- src/index.js
- webpack.config.js
This adds the ability to create a UMD build of the library via a 'dist' npm script.
> Add UMD build

- README.md
FIx the README to correctly add a type to the <Button/>
> Add required prop 'type' to Button in documentation

- packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
- packages/visual-stack/src/components/Filters.js
The MultiSelectFilter was broke.
We unbroke it.
> Updated MultiSelectFilter to handle single checkbox selection correctly

- packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
- packages/visual-stack/package.json
- packages/visual-stack/src/components/Filters.js
- packages/visual-stack/test/components/MultiSelectFilterTest.js
Added some testing around the MultiSelectFilter component
> MultiSelectFilter testing

- .travis.yml
- packages/visual-stack/package.json
Upgrade react-svg to the latest and drop Node 4 in travis
> React svg upgrade

- packages/visual-stack/src/components/Filters.css
- packages/visual-stack/src/components/Filters.js
- packages/visual-stack/src/components/SlidingPanel.css
Added overflow scrolling to filters in slidingpanel & background color on hover
> Sliding panel filter scrolling

- packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
- packages/visual-stack/src/components/Filters.css
- packages/visual-stack/src/components/Filters.js
When MultiSelectFilter has no option given to it, the 'Select All' checkbox should not show up.
> Fix zero state for MultiSelectFilter

- packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
- packages/visual-stack/src/components/SlidingPanel.css
- packages/visual-stack/src/components/SlidingPanel.js
The Sliding Panel Toggle Button should have a customizable tooltip.
> Tooltip on for Sliding Panel Toggle Button

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
- packages/visual-stack/src/components/Filters.js
If "selectAll" option was selected, but there were no values to display, the MultiSelectFilter would show nothing instead of a Zero State.
> Fix Bug in MultiSelectFilter Zero State

- README.md
- packages/visual-stack-docs/package.json
- packages/visual-stack-docs/src/containers/App/SideNav.js
- packages/visual-stack-docs/src/containers/App/index.js
- packages/visual-stack-redux/src/actions.js
- packages/visual-stack-redux/src/components/SideNav.js
- packages/visual-stack-redux/src/components/TopNav.js
- packages/visual-stack-redux/src/layouts/ApplicationLayout/index.js
- packages/visual-stack-redux/test/actions.test.js
- packages/visual-stack-redux/test/components/SideNav.test.js
- packages/visual-stack-redux/test/components/TopNav.test.js
- packages/visual-stack/package.json
- packages/visual-stack/src/components/SideNav.css
- packages/visual-stack/src/components/SideNav.js
- packages/visual-stack/src/components/TopNav.js
- packages/visual-stack/src/layouts/ApplicationLayout/index.js
- packages/visual-stack/src/layouts/ApplicationLayout/style.css
- packages/visual-stack/test/components/SideNavTest.js
Added collapsing capability to SideNav component in visual stack.
> Make SideNav Collapsable 

- packages/visual-stack-docs/src/containers/App/SideNav.js
- packages/visual-stack-redux/src/components/SideNav.js
- packages/visual-stack/src/components/SideNav.js
Allows for the sidenav initial state to be set by prop.
> Gave sidenav the ability to set its initial state

- packages/visual-stack/src/components/SideNav/SideNav.js
- packages/visual-stack/src/components/SlidingPanel.css
> Update sliding panel css

- packages/visual-stack/src/components/SideNav/SideNav.css
Changed from grays to deep blackish-blue
> Update colors for the sidenav

- packages/visual-stack-docs/src/containers/App/SideNav.js
- packages/visual-stack-docs/src/containers/Components/Docs/index.js
- packages/visual-stack-docs/src/containers/Components/Docs/sidenav.js
- packages/visual-stack-docs/src/containers/Components/Docs/table.js
- packages/visual-stack/src/components/Icons/index.js
- packages/visual-stack/src/components/Table/Table.css
- packages/visual-stack/src/components/Table/Table.js
- packages/visual-stack/src/components/Table/index.js
Super simple MVP table component with custom styling and some mobile responsiveness.
> Table component

- packages/visual-stack-redux/src/components/SideNav/SideNav.js
- packages/visual-stack-redux/test/components/SideNav/SideNav.test.js
- packages/visual-stack/src/components/SideNav/SideNav.css
- packages/visual-stack/src/components/SideNav/SideNav.js
- packages/visual-stack/src/components/SideNav/UserMenu.js
- packages/visual-stack/test/components/SideNavTest.js
Main reason for this PR: Make UserMenu background similar to SideNav background.
I had two ways I could implement this. Either force the user to pass in the prop when they create UserMenu (which means different colors could be used), or pass it in via SideNav. 
I implemented the later to force it to be the same. I would love a second opinion on this!
> Made UserMenu gets background color from SideNav

- packages/visual-stack-redux/src/components/SideNav/SideNav.js
- packages/visual-stack-redux/test/components/SideNav/SideNav.test.js
- packages/visual-stack/src/components/SideNav/SideNav.js
- packages/visual-stack/test/components/SideNavTest.js
Updated Sidenav code so it can handle cases where no UserMenu will be passed into it.
> Sidenav fix

- packages/visual-stack/src/components/Filters.css
- packages/visual-stack/src/components/SlidingPanel.css
> Slider Panel UI Styling Update

- packages/visual-stack-docs/package.json
- packages/visual-stack-redux/package.json
- packages/visual-stack-redux/webpack.config.js
- packages/visual-stack/package.json
- packages/visual-stack/postcss.config.js
- packages/visual-stack/webpack.config.babel.js
Upgrade to a recent webpack + plugins.
Also added a 'clean' target to the docs package.
> Webpack 3 Upgrade

- packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
- packages/visual-stack/src/components/Filters.css
- packages/visual-stack/src/components/SlidingPanel/SlidingPanel.css
- packages/visual-stack/src/layouts/ApplicationLayout/style.css
Various UI changes to the Sliding Panel and MultiSelectFilter component 
- Updated the width of the sliding panel
- Added overflow scroll so sliding panel dropdowns won't be cut off
- Fixed inconsistent sized checkboxes in MultiSelectFilter
> Updated sliding panel UI

- packages/visual-stack/src/components/SlidingPanel/SlidingPanel.css
- packages/visual-stack/src/components/SlidingPanel/index.js
Updated the styles for the filter toggle btn and fixed the scrolling issue.
> Updates to sliding panel styles

- packages/visual-stack-docs/src/containers/App/SideNav.js
- packages/visual-stack-redux/src/components/SideNav/SideNav.js
- packages/visual-stack-redux/src/components/SideNav/index.js
- packages/visual-stack/src/components/Icons/index.js
- packages/visual-stack/src/components/SideNav/Icons.js
- packages/visual-stack/src/components/SideNav/LinkGroup.js
- packages/visual-stack/src/components/SideNav/UserMenu.js
- packages/visual-stack/src/components/SideNav/index.js
Added a SettingsLink as children of UserMenu
> SettingsLink in UserMenu

- packages/visual-stack-redux/package.json
- packages/visual-stack-redux/src/components/MenuBar.js
- packages/visual-stack-redux/test/components/MenuBar.test.js
- packages/visual-stack-redux/test/setup.js
This PR removes jquery from visual-stack-redux
> Remove jquery

- packages/visual-stack/src/components/SideNav/SideNav.css
Adds the changes we discussed in front end chapter meeting.
> Prevent the last couple of elements in a side nav from falling under the user menu and toggle icon

- .gitignore
- package-lock.json
- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/package-lock.json
Necessary to make sure the correct versions of certain packages are being installed in remote builds.
> Adding package-lock.json again to visual stack.

- package.json
- packages/visual-stack/src/components/PageContent.css
- packages/visual-stack/src/components/PageHeader.css
- packages/visual-stack/src/layouts/ApplicationLayout/style.css
Addresses issue #96 
Also removes an accidental dependency that was added into the package.
> Page header fix

- packages/visual-stack-docs/src/containers/GettingStarted/democode.js
- packages/visual-stack-docs/src/containers/GettingStarted/index.js
- packages/visual-stack-redux/src/layouts/ApplicationLayout/index.js
- packages/visual-stack/src/components/TabLayout/index.js
- packages/visual-stack/src/layouts/ApplicationLayout/index.js
- packages/visual-stack/src/layouts/ApplicationLayout/style.css
Refactored application layout code so the bar header would no longer resize when a sliding panel is expanded or collapsed
> Addresses issue #116:

- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/PageContent.css
- packages/visual-stack/src/components/PageHeader.css
- packages/visual-stack/src/components/SideNav/SideNav.js
- packages/visual-stack/src/layouts/ApplicationLayout/style.css
Apply white background to topbar and add box-shadow for depth
> Topbar ui updates

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack-redux/src/actions.js
- packages/visual-stack-redux/src/components/SlidingPanel.js
- packages/visual-stack-redux/test/components/SlidingPanel.test.js
- packages/visual-stack/src/components/PageContent.css
- packages/visual-stack/src/components/SideNav/SideNav.css
- packages/visual-stack/src/components/SlidingPanel/SlidingPanel.css
- packages/visual-stack/src/components/SlidingPanel/index.js
- packages/visual-stack/test/components/SlidingPanelTest.js
- Use flexbox instead of fixed positioning, so it's easier for the sliding panel to push sibling elements around.
- Adjust doc site to use the new layout.
> Upstream sliding panel changes for insights

- CONTRIBUTING.md
- Procfile
- package.json
- packages/visual-stack-docs/package.json
- packages/visual-stack-docs/run-watch.sh
- packages/visual-stack-docs/src/containers/GettingStarted/democode.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack-redux/run-watch.sh
- packages/visual-stack/run-watch.sh
- packages/visual-stack/src/css/base.css
Adding some tooling to facilitate making changes across the mono-repo
> Infrastructure improvements

- .travis.yml
- package-lock.json
- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/package-lock.json
> Deployment fix

- .travis.yml
Unpin the node version since node updated to fix the jest issue (see issue #161)
> Unpin node version

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Layouts/DialogLayout/index.js
- packages/visual-stack/src/components/CollapsiblePanel.css
- packages/visual-stack/src/components/Form.css
- packages/visual-stack/src/layouts/DialogLayout/index.css
dialog layout defaults to a smaller width
> Dialog layout style

- .eslintrc.json
- packages/visual-stack-docs/src/containers/Components/Docs/form.js
- packages/visual-stack-docs/src/containers/Components/Docs/select.js
- packages/visual-stack/package-lock.json
- packages/visual-stack/package.json
- packages/visual-stack/src/components/CreatableSelect/CreatableSelect.css
- packages/visual-stack/src/components/CreatableSelect/index.js
- packages/visual-stack/src/components/CreatableSelect/tests/CreatableSelect.test.js
- packages/visual-stack/src/components/Select/index.js
- packages/visual-stack/src/components/Select/tests/Select.test.js
Adding Creatable Select Component
> Creatable select

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Layouts/DialogLayout/index.js
- packages/visual-stack-docs/src/index.js
- packages/visual-stack/src/layouts/DialogLayout/index.js
- packages/visual-stack/src/layouts/DialogLayout/tests/index.test.js
- Make submit and cancel on DialogLayout optional
> Dialog layout view

- packages/visual-stack-docs/src/containers/Components/Docs/select.js
- packages/visual-stack/src/components/CreatableSelect/CreatableSelect.css
- packages/visual-stack/src/components/Select/Select.css
Paired with @danchong to style the multiselect values for react-select v2.  Improve the documentation of the Select components to include an example of a non-creatable multiselect as well as the imports necessary to use the Select components.
> Add styles for react-select multiselects

- packages/visual-stack-docs/src/containers/Components/Docs/index.js
- packages/visual-stack-docs/src/containers/Components/Docs/pagination.js
- packages/visual-stack-redux/src/actions.js
- packages/visual-stack-redux/src/components/Pagination/index.js
- packages/visual-stack-redux/src/components/Pagination/tests/index.test.js
- packages/visual-stack-redux/test/actions.test.js
- packages/visual-stack/src/components/Pagination/index.js
- packages/visual-stack/src/components/Pagination/style.css
- packages/visual-stack/src/components/Pagination/tests/index.test.js
- packages/visual-stack/src/components/Select/index.js
added a new component for pagination
> Pagination

- packages/visual-stack-docs/src/containers/Components/Docs/listview.js
- packages/visual-stack/src/components/ListView/index.js
- packages/visual-stack/src/components/ListView/style.css
- packages/visual-stack/src/components/ListView/tests/index.test.js
adding a loading state for the list view
> add a loading state to listview

- packages/visual-stack/src/components/SlidingPanel/index.js
allowing classnames to be passed in to sliding panel components
> Adding className to SlidingPanel

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/button-with-dropdown.js
- packages/visual-stack-docs/src/containers/Components/Docs/index.js
- packages/visual-stack/src/components/ButtonWithDropdown/index.js
- packages/visual-stack/src/components/ButtonWithDropdown/styles.css
- packages/visual-stack/src/components/ButtonWithDropdown/tests/index.test.js
Add a component that has a button and a dropdown area that expands the dropdown area when the button is clicked.
> Add ButtonWithDropdown component

- packages/visual-stack-redux/src/components/SlidingPanel.js
- packages/visual-stack-redux/test/components/SlidingPanel.test.js
Also, cleaning up and simplifying some of the code.
> Pass visual-stack-redux SlidingPanel props through to visual-stack component

- CHANGELOG.md
- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-docs/package.json
- packages/visual-stack-docs/src/containers/Components/Docs/datepicker.js
- packages/visual-stack-docs/src/containers/Components/Docs/index.js
- packages/visual-stack-redux/src/actions.js
- packages/visual-stack-redux/src/components/DatePicker/index.js
- packages/visual-stack-redux/test/actions.test.js
- packages/visual-stack/package-lock.json
- packages/visual-stack/package.json
- packages/visual-stack/src/components/ButtonWithDropdown/styles.css
- packages/visual-stack/src/components/DatePicker/DatePicker.css
- packages/visual-stack/src/components/DatePicker/DatePickerButton.js
- packages/visual-stack/src/components/DatePicker/index.js
- packages/visual-stack/src/components/DatePicker/tests/DatePickerButton.test.js
- packages/visual-stack/src/components/DatePicker/tests/index.test.js
Add a polished version of Insight's date picker component.
> Insights datepicker

- package-lock.json
- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-docs/src/containers/Components/Docs/select.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/AsyncSelect/AsyncSelect.css
- packages/visual-stack/src/components/AsyncSelect/index.js
- packages/visual-stack/src/components/AsyncSelect/tests/AsyncSelect.test.js
Adding an AsyncSelect Component that you may want to load options from a remote source (e.g. fetching as a user types)
> Adding AsyncSelect Component from react select

- packages/visual-stack-docs/src/containers/Components/Docs/button.js
- packages/visual-stack/src/components/Button.css
- packages/visual-stack/src/components/Button.js
Created a new button type in Button component and in Visual Stack Docs to be used for inline toolbar styles.
> new button type

- packages/visual-stack-docs/src/containers/Components/Docs/button-with-dropdown.js
- packages/visual-stack-docs/src/containers/Components/Docs/datepicker.js
- packages/visual-stack/src/components/DatePicker/DatePickerButton.js
- packages/visual-stack/src/components/DatePicker/index.js
- packages/visual-stack/src/components/DatePicker/tests/index.test.js
The user of this component sometimes needs to know which named ranges are selected.
> Have DatePicker pass the namedRanges to the onApply callback

- packages/visual-stack/src/layouts/DialogLayout/index.css
- packages/visual-stack/src/layouts/DialogLayout/index.js
Changed DialogLayout header to 64px and improve css to center by align-item center rather than padding
> Changed DialogLayout styling

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/card.js
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/AnalyticCard/index.js
- packages/visual-stack/src/components/AnalyticCard/style.css
- packages/visual-stack/src/components/AnalyticCard/tests/AnalyticCard.test.js
Passes onClick to analytic cards. Adds onHover styling for clickable cards
> Adds clickable analytic cards

- packages/visual-stack/src/components/SlidingPanel/SlidingPanel.css
- packages/visual-stack/src/components/SlidingPanel/index.js
Changed the rounded icon button for the sliding panel component to the rounded square -- inline-outline-secondary button.
> Changed the sliding panel button to use the inline-secondary-btn

- CHANGELOG.md
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack-redux/src/actions.js
- packages/visual-stack-redux/src/components/SlidingPanel.js
- packages/visual-stack-redux/test/actions.test.js
- packages/visual-stack-redux/test/components/SlidingPanel.test.js
fixing the bug in dropdown filter when remounting the same component.
> Fix dropdown filter state

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/App/SideNav.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack-redux/src/actions.js
- packages/visual-stack-redux/src/components/SideNav/CategoryLabel.js
- packages/visual-stack-redux/src/components/SideNav/LinkGroup.js
- packages/visual-stack-redux/src/components/SideNav/index.js
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/SideNav/CategoryLabel.js
- packages/visual-stack/src/components/SideNav/SideNav.css
- packages/visual-stack/src/components/SideNav/index.js
- packages/visual-stack/src/components/SideNav/tests/index.test.js
create a category label to separate different sections in the side nav
> add a category label to side nav

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/table.js
- packages/visual-stack-redux/src/components/DataTable/index.js
- packages/visual-stack/src/components/Table/DataTable/DataTable.css
- packages/visual-stack/src/components/Table/DataTable/Trend.js
- packages/visual-stack/src/components/Table/DataTable/index.js
- packages/visual-stack/src/components/Table/DataTable/tests/index.test.js
> Data table trend

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/table.js
- packages/visual-stack-redux/src/components/DataTable/index.js
- packages/visual-stack-redux/src/components/DataTable/tests/index.test.js
- packages/visual-stack/src/components/Table/DataTable/DataTable.css
- packages/visual-stack/src/components/Table/DataTable/index.js
- packages/visual-stack/src/components/Table/DataTable/tests/index.test.js
> Render Toolbar in data table

- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-docs/src/containers/Components/Docs/card.css
- packages/visual-stack-docs/src/containers/Components/Docs/card.js
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/AnalyticCard/index.js
- packages/visual-stack/src/components/AnalyticCard/style.css
- packages/visual-stack/src/components/AnalyticCard/tests/index.test.js
- packages/visual-stack/src/components/SideNav/SideNav.css
- packages/visual-stack/src/css/base.css
Analytic Cards:
- Update card styling
- Update cards in docs
VS Base Styles:
- Add font smoothing for improved browser text rendering
> Styling updates to Analytic Cards UI

- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-docs/src/containers/Components/Docs/button-with-dropdown.js
- packages/visual-stack-docs/src/containers/Components/Docs/button.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/Button.css
- packages/visual-stack/src/components/Button.js
- packages/visual-stack/src/components/SlidingPanel/SlidingPanel.css
- Adjust icon button hover svg color
- Move deprecated buttons (styles are still in the css in case they are still being used in some places.
- Add Small Button Type
> Update Button Docs

- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-docs/src/containers/Components/Docs/expanding-input-button.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/ExpandingInputButton/styles.css
Style Updates:
- add expanding animation
- adjust svg sizes, hover interactions
> update styling, add animation/transitions

- CHANGELOG.md
- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-docs/src/containers/Components/Docs/listview.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/ListView/index.js
- packages/visual-stack/src/components/ListView/tests/index.test.js
adding an empty state to list view
> adding an empty state to list view

- packages/visual-stack-docs/src/components/Demo/styles.css
- packages/visual-stack-docs/src/containers/Components/Docs/alert.js
- packages/visual-stack/src/components/Alert/Alert.css
- packages/visual-stack/src/components/Alert/index.js
- packages/visual-stack/src/components/Alert/tests/Alert.test.js
Update icon, text, and button styles.
Could we also add the ability to enter html into the content message? For example, we may have use-cases that require a heading and a couple paragraphs.
> Alert styles

- CHANGELOG.md
- packages/visual-stack/src/components/Modal.js
- packages/visual-stack/src/components/tests/Modal.test.js
- Fix Escape listener cleanup on Modal
> Fix Escape listener for Modal

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/index.js
- packages/visual-stack-docs/src/containers/Components/Docs/popover.css
- packages/visual-stack-docs/src/containers/Components/Docs/popover.js
- packages/visual-stack/package-lock.json
- packages/visual-stack/package.json
- packages/visual-stack/src/components/Popover/Popover.css
- packages/visual-stack/src/components/Popover/index.js
- packages/visual-stack/src/components/Popover/tests/Popover.test.js
- Added Popover component
- Also included a stateful HoverPopover that shows the popover on hover
> Popover Component

- packages/visual-stack-docs/src/containers/Components/Docs/modal.js
- packages/visual-stack/src/components/Modal.css
Updates  include:
- Adjust modal title font size
- Replace button styles in docs
> Update modal styles, docs

- packages/visual-stack/src/components/CollapsiblePanel.css
Update header styles:
- Add font-weight: 500; for collapsible panel type 2
> Update panel header title styles

- CHANGELOG.md
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/Form.js
- packages/visual-stack/src/components/tests/Form.test.js
add required sign to form components
> add required sign to form components

- packages/visual-stack/package-lock.json
- packages/visual-stack/package.json
- packages/visual-stack/src/components/CJLogo.js
- packages/visual-stack/src/components/IconInfo.js
- packages/visual-stack/src/components/IconSuccess.js
- packages/visual-stack/src/components/IconWarning.js
> use react-inlinesvg instead of react-svg

- packages/visual-stack-docs/src/containers/Components/Docs/blankslate.js
- packages/visual-stack/src/components/BlankSlate/index.js
fix blankslate prop type and doc error
> fix blankslate prop type and doc error

- packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
> Fixed Sliding Panel Typo

- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-docs/src/containers/Components/Docs/button.css
- packages/visual-stack-docs/src/containers/Components/Docs/button.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/Button.css
- packages/visual-stack/src/components/Button.js
Adding new button styles for the mweb-platform transition
> UI pill buttons

- CHANGELOG.md
- packages/visual-stack/src/components/Form.js
- packages/visual-stack/src/components/tests/Form.test.js
SelectField passes options to Select and not to Field/Label
> SelectField passes options to Select and not to Field/Label

- packages/visual-stack-docs/src/containers/Components/Docs/button.js
- packages/visual-stack/src/components/Button.css
- packages/visual-stack/src/components/Button.js
> Add New Button type

- .github/workflows/ci.yml
- Builds on push to any branch
- Deploys visual-stack-docs to S3 only on push to master
- Pull requests depend on the action build status
> Build and deploy using a GitHub Action instead of Travis

- .github/workflows/ci.yml
Deploy to a new visual-stack-docs S3 bucket
> GitHub action docs

- CHANGELOG.md
- packages/visual-stack-docs/package-lock.json
- packages/visual-stack-docs/src/containers/Experimental/Docs/box.js
- packages/visual-stack-docs/src/containers/Experimental/Docs/text.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/package-lock.json
- packages/visual-stack/src/components/Button.css
- packages/visual-stack/src/experimental/Box/Box.css
- packages/visual-stack/src/experimental/Box/index.js
- packages/visual-stack/src/experimental/Box/tests/index.test.js
- packages/visual-stack/src/experimental/Text/Text.css
- packages/visual-stack/src/experimental/Text/index.js
- packages/visual-stack/src/experimental/Text/tests/index.test.js
Removes wrap prop from Box
Adds Text error and error-small types
Make Button min-width fit-content so that it plays well with flexbox
> Box and Text updates

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/form.js
- packages/visual-stack/src/components/Form/Input.js
- packages/visual-stack/src/components/tests/Form.test.js
Adds a trimmed prop to Input that calls the onChange prop on blur with the value trimmed.
Can also be used in TextField since it wraps Input.
> Add trimmed prop to Input

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/form.js
- packages/visual-stack/src/components/Form/TextArea.js
- packages/visual-stack/src/components/tests/Form.test.js
Adds a trimmed prop to TextArea that calls the onChange prop on blur with the value trimmed.
Same as the trimmed prop in Input.
> Add trimmed prop to TextArea

- packages/visual-stack/src/experimental/Box/Box.css
> fix css classname

- packages/visual-stack/src/experimental/Box/Box.css
> fix css typo

- packages/visual-stack/src/experimental/Tree/index.js
> fix tree component warnings

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/table.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack-redux/package.json
- packages/visual-stack-redux/src/actions.js
- packages/visual-stack-redux/src/components/DataTable/index.js
- packages/visual-stack-redux/src/components/DataTable/tests/index.test.js
- packages/visual-stack-redux/test/actions.test.js
- packages/visual-stack/src/components/Table/DataTable/index.js
- packages/visual-stack/src/components/Table/DataTable/sortingHelper.js
- packages/visual-stack/src/components/Table/DataTable/tests/index.test.js
Adding an option to allow selectable rows in the data table.
> Add selected rows to data table

- packages/visual-stack/src/components/Modal.js
Allow passing additional className props to the various components within Modal to add additional styles. className would be overwritten before with the static classNames in the inner components
> Changed Modal components to allow passing in additional className props

- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/src/experimental/TriStateCheckbox/index.js
- packages/visual-stack/src/experimental/TriStateCheckbox/tests/index.test.js
Remove check on tri-state checkbox for prevProps to have updateInnerCheckBoxState update all the time
> Remove check on tri-state checkbox for prevProps

- CHANGELOG.md
- packages/visual-stack-docs/src/containers/Components/Docs/topnav.js
- packages/visual-stack-redux/package-lock.json
- packages/visual-stack/src/components/TopNav/BackToCjLink.js
- packages/visual-stack/src/components/TopNav/CjSupportLink.js
- packages/visual-stack/src/components/TopNav/TopNav.css
- packages/visual-stack/src/components/TopNav/TopNav.js
- packages/visual-stack/src/components/TopNav/tests/index.test.js
Add subtitle slot on TopNav
https://cj.invisionapp.com/share/TH1045QWWJZV#/screens/442292573
> Cjpm 18122
