cjdev/visual-stack

src/components/Button.js

R.concat is a binary function so classNames weren't being appended.

Fix appending of classNames in Button.js

---

CHANGELOG.md
packages/visual-stack-docs/src/containers/Components/Docs/slidingpanel.js
packages/visual-stack-redux/src/components/SlidingPanel.js
packages/visual-stack/src/components/SlidingPanel.js

Fixed a bug where redux could not assign a unique id for a sliding panel dropdown due to translation issue. Now when creating a sliding panel dropdown, a unique id must be supplied.

Gave sliding panel dropdowns unique id's to allow for label translations

---

packages/visual-stack/src/components/SlidingPanel.css

Sliding Panel should shift down lower to not block header title in App Layout.

Sliding Panel should shift down.

---

packages/visual-stack/src/components/Spinner.js

Falling back to the default FA spin, as our override is non-existent?

Fix non-spinning spinner

---

packages/visual-stack-docs/src/containers/App/SideNav.js
packages/visual-stack-redux/src/components/SideNav.js
packages/visual-stack/src/components/SideNav.css

2 small changes following on from version 1.2.0.
* Fix SideNav entries such that they do not wrap during the collapse animation.
* Re-export the LinkContentWrapper through visual-stack-redux such that consuming applications do not have to reference both 'visual-stack' and 'visual-stack-redux' to use the SideNav.

Side nav fixes

---

packages/visual-stack-redux/package.json
packages/visual-stack-redux/src/components/MenuBar.js
packages/visual-stack-redux/src/components/SideNav/LinkGroup.js
packages/visual-stack-redux/src/components/SideNav/SideNav.js
packages/visual-stack-redux/src/components/SlidingPanel.js
packages/visual-stack/package.json
packages/visual-stack/src/components/BlankSlate.js
packages/visual-stack/src/components/Button.js
packages/visual-stack/src/components/CJLogo.js
packages/visual-stack/src/components/Filters.js
packages/visual-stack/src/components/Form.js
packages/visual-stack/src/components/List.js
packages/visual-stack/src/components/MenuBar.js
packages/visual-stack/src/components/Modal.js
packages/visual-stack/src/components/Panel.js
packages/visual-stack/src/components/SideNav/Header.js
packages/visual-stack/src/components/SideNav/LinkGroup.js
packages/visual-stack/src/components/SideNav/SideNav.js
packages/visual-stack/src/components/SlidingPanel.js
packages/visual-stack/src/components/Spinner.js

In preparation for a React 16 upgrade, this PR migrates all our usage of PropTypes from React to the prop-types library

Migrate from React.PropTypes to prop-types lib

---

packages/visual-stack-docs/src/containers/Components/Docs/table.css
packages/visual-stack-docs/src/containers/Components/Docs/table.js
packages/visual-stack-docs/src/containers/Components/index.css
packages/visual-stack-docs/src/containers/Components/index.js
packages/visual-stack/src/components/Table/Table.css
packages/visual-stack/src/components/Table/Table.js
packages/visual-stack/src/components/Table/index.js

This PR makes the following changes to `Table` and related components:
- All components accept a `className` prop
- All components accept and forward unhandled props to the underlying React component
- Adds `right`, `center`, and `nowrap` shorthand props to `Td` and `Th`
- Removes the `TdRight` component in favor of `<Td right>`
- Renames all CSS classes with a `vs-` prefix
- Expands the documentation to explain the changes

Table component improvements

---

packages/visual-stack-docs/src/containers/Components/Docs/form.js
packages/visual-stack-docs/src/containers/Components/Docs/index.js
packages/visual-stack/src/components/Form.css
packages/visual-stack/src/components/Form.js

Form components uses bootstrap css for styling, so name spacing it will break the component itself.
This PR also includes a VERY minimal document for the Form component, so this kind of error can be checked for (at least manually by visual testing) 
Addresses #107 and will hopefully be the last PR for #95

Fix Form Component

---

packages/visual-stack-docs/src/containers/Components/Docs/button.js
packages/visual-stack/src/components/Button.css
packages/visual-stack/src/components/Button.js

Work in progress. Adding new platform buttons to test and gather feedback with the intent to replace the old buttons in a future commit.
- Changed primary cj green to teal.
- Added new buttons future platform vision
- Minimal changes to existing buttons structure. Need to test the new 4px top and bottom margins to the default buttons.
- Need more testing for icon+text buttons to make sure svg lines up correctly
- Need to add remaining states (disabled, active, focus)

Add New Platform buttons

---

packages/visual-stack/src/components/CJLogo.css
packages/visual-stack/src/components/PageContent.css
packages/visual-stack/src/components/PageHeader.css
packages/visual-stack/src/components/SideNav/SideNav.css
packages/visual-stack/src/layouts/ApplicationLayout/style.css

Apply 8px unit system of measurement for optimized rendering for devices/displays. 
- Deepen box-shadow for page-header
- Adjust sidenav logo/icon sizing for 8px 
- Increase pageContent padding to 24px 
- sideNav width increased to 256px
- collapsed sideNav width decreased to 48px
- topbar min-height increased to 48px

Update layout metrics (8px unit system)

---

packages/visual-stack-redux/src/components/SideNav/SideNav.js

To match the member user menu, we need to add a privacy policy link and a copyright statement to the top of the UserMenu, before the LogoutLink.

CJPM-10596: move logout link to end of user menu

---

package-lock.json
package.json
packages/visual-stack-docs/package-lock.json
packages/visual-stack-redux/package-lock.json
packages/visual-stack/package-lock.json

Simple update of Lerna to the latest version. `npm audit` was warning of an issue with one of its dependencies: https://npmjs.com/advisories/755

upgrade lerna to latest version

---

package-lock.json
packages/visual-stack-docs/package-lock.json
packages/visual-stack-redux/package-lock.json
packages/visual-stack/package-lock.json
packages/visual-stack/src/components/Select/Select.css

Removed height from Select Component to fix style for when isMulti is true, to fit all selected values. Before this commit, the styling looked weird when isMulti is enabled and you select more items than fits the component.
Before:
After:

Select Component should expand to fit all values when isMulti is enabled

---

package-lock.json
packages/visual-stack-docs/src/containers/Components/Docs/form.js
packages/visual-stack-docs/src/containers/Components/Docs/select.js
packages/visual-stack-docs/src/containers/Layouts/DialogLayout/index.js
packages/visual-stack-docs/src/index.js
packages/visual-stack/src/components/CreatableSelect/CreatableSelect.css
packages/visual-stack/src/components/Select/Select.css
packages/visual-stack/src/components/Select/tests/Select.test.js
packages/visual-stack/src/components/SideNav/SideNav.js
packages/visual-stack/src/components/SideNav/UserMenu.js
packages/visual-stack/src/components/TabLayout/tests/index.test.js
packages/visual-stack/src/css/forms.css
packages/visual-stack/src/layouts/DialogLayout/index.js
packages/visual-stack/src/layouts/DialogLayout/tests/index.test.js

This fixes placeholder font styles for textareas by applying the styles to textareas too and not just inputs. The difference was made more noticeable when rendering inputs and textareas next to each other.
It also adds a sensible height default to textareas for consistency sake, avoiding having to manually specify the height on each use.
Also applies prettier project wide and fixes all other eslint errors and warnings. Could be an opportunity to start enforcing eslint at build time.

Fix TextArea styles and lint errors

---

packages/visual-stack-docs/src/containers/Components/Docs/button-with-dropdown.js
packages/visual-stack/src/components/ButtonWithDropdown/index.js
packages/visual-stack/src/components/ButtonWithDropdown/tests/index.test.js

Use a render prop for the button instead of passing in a component: this makes 
it easier to specify how the button renders without having to worry about React's 
rules around component identity (see the date picker PR for an example).
Also, fixes issue @fhwrdh noticed here, also tweak the button text in the docs: https://github.com/cjdev/visual-stack/pull/182#issuecomment-493713780

Improve ButtonWithDropdown

---

packages/visual-stack-redux/package-lock.json
packages/visual-stack-redux/src/components/SideNav/LinkGroup.js
packages/visual-stack-redux/test/components/SideNav/LinkGroup.test.js

We'd like to be able to pass a prop to LinkGroups that makes the expanded state enabled by default

Passing in initialActive as true will call toggleSideNavLinkGroup

---

CHANGELOG.md
package.json
packages/visual-stack-docs/src/containers/Components/Docs/datepicker.js
packages/visual-stack/src/components/DatePicker/index.js
packages/visual-stack/src/components/DatePicker/tests/index.test.js

The callback for the datepicker now gets the ids of the currently selected sidebar ranges.  This is a backwards-compatible change because we added an argument to the callback.

Datepicker cb named ranges

---

packages/visual-stack/src/components/SideNav/SideNav.css

Currently set at max-height of 768px which cuts off the rest of the items. Example can be seen in visual-stack-docs/components/ (spinner, tablayout, table pages are hidden)

Remove inner submenu ul max-height to show all menu links

---

packages/visual-stack-redux/src/components/SlidingPanel.js
packages/visual-stack-redux/test/actions.test.js
packages/visual-stack-redux/test/components/SlidingPanel.test.js

Both of these components had a bug where if they were destroyed and brought back (i.e. switching routes on a multi-page app) they would lose state if you used intiial active.
I changed it to use initialActive only when state coming from the store is undefined, otherwise it respects the stored state even if for some reason the constructor is called again.

SlidingPanel and SlidingPanelDropdown now respect state

---

packages/visual-stack-docs/src/containers/Components/Docs/modal.js
packages/visual-stack/src/components/Modal.js
packages/visual-stack/src/components/tests/Modal.test.js

Similar to onBackgroundClick, a new prop intended to be used for closing the Modal when the Escape key is pressed

Add onEscapeKeyUp function to Modal

---

packages/visual-stack/src/css/base.css

Update pre styles to white-space: pre-wrap, to allow page to resize past pre elements. Need a better fix in the future.

Update <pre> and <code> styles

---

CHANGELOG.md
packages/visual-stack/src/components/Form.js

react-select props passed to SelectField - results in react throwing warning logs. Passing react-select props only to react-select with this change.

SelectField passes react-select props only to react-select

---

packages/visual-stack/src/components/SideNav/SideNav.css

This fixes the docs to show all components in the sidenav.

Make SideNav max-height fit-content instead of fixed height

---

packages/visual-stack/package-lock.json
packages/visual-stack/src/components/CollapsiblePanel.js

- Spread only rest props instead of all props
- Refactor to use classNames

Spread only rest props on CollapsiblePanel

---

CHANGELOG.md
packages/visual-stack/src/components/SideNav/SideNav.js
packages/visual-stack/src/components/SideNav/tests/index.test.js

omit VS props from being passed to SideNav ul so that we can stop react warnings

omit VS props from being passed to SideNav ul

---

packages/visual-stack/src/experimental/Box/index.js

- Remove console warning on experimental Box since it adds noise during testing.

Remove console warning on experimental Box

---

packages/visual-stack-docs/src/containers/Components/Docs/tablayout.js
packages/visual-stack-redux/CHANGELOG.md
packages/visual-stack-redux/src/components/TabLayout.js
packages/visual-stack-redux/test/components/TabLayout.test.js
packages/visual-stack/src/components/TabLayout/index.js

1. Adds optional 'lazy' prop to TabLayout, making it render tab content only when the tab is selected.
2. Adds optional 'renderContent' prop to Tab, taking a function to render the content.

Add ability for tabs to render lazily

---

packages/visual-stack/src/components/SideNav/CategoryLabel.js

Omit properties that doesn't belong in dom nodes to avoid errors in DevTools

CategoryLabel.js: omit properties that doesn't exist in DOM

---

packages/visual-stack/src/layouts/DialogLayout/index.css
packages/visual-stack/src/layouts/DialogLayout/index.js
packages/visual-stack/src/layouts/DialogLayout/tests/index.test.js

DialogLayout and TopNav were both adding margin to the top, between the TopNav and the content. This caused the DialogLayout to have double the spacing at the top. This removes DialogLayout's content styling and just passes children down to TopNav

DialogLayout now uses TopNav content
